
export interface CalendarEventData {
  title: string;
  description: string;
  start_time: string;
  end_time: string;
  user_id: string;
  location?: string;
  color?: string;
}

export interface EventMetadata {
  courseId: string;
  studentId: string;
  teacherId: string;
  courseType: string;
  courseTitle: string;
  courseSkill?: string;
  courseLevel?: string;
  studentName: string;
  teacherName: string;
  isAutoGenerated: boolean;
  sessionNumber?: number;
  totalSessions?: number;
  durationMinutes: number;
  replacesAvailabilitySlot?: string;
  originalSlotTime?: string;
  dayOfWeek?: number;
  isOneTime?: boolean;
}

export interface CourseDetails {
  title: string;
  duration: string;
  course_type: string;
  skill?: string;
  level?: string;
  instructor_ids?: string[];
}

export interface UserDetails {
  first_name: string;
  last_name: string;
}
