
import { supabase } from '@/integrations/supabase/client';
import { v4 as uuidv4 } from 'uuid';
import { toast } from 'sonner';

export interface CalendarEventData {
  title: string;
  description: string;
  start_time: string;
  end_time: string;
  user_id: string;
  location?: string;
  color?: string;
}

export function useCalendarEventCreation() {
  
  // Create calendar events for recurring courses
  const createRecurringEvents = async (
    courseId: string,
    studentId: string,
    teacherId: string,
    availabilitySlot?: any,
    courseData?: any
  ) => {
    try {
      console.log('Creating recurring events for enrollment:', { courseId, studentId, teacherId });
      
      if (!availabilitySlot) {
        console.log('No availability slot provided for recurring course');
        return false;
      }

      // Get course details
      const { data: course, error: courseError } = await supabase
        .from('courses')
        .select('title, duration, course_type')
        .eq('id', courseId)
        .single();

      if (courseError || !course) {
        console.error('Error fetching course details:', courseError);
        return false;
      }

      // Get teacher details
      const { data: teacher, error: teacherError } = await supabase
        .from('custom_users')
        .select('first_name, last_name')
        .eq('id', teacherId)
        .single();

      if (teacherError || !teacher) {
        console.error('Error fetching teacher details:', teacherError);
        return false;
      }

      // Get student details
      const { data: student, error: studentError } = await supabase
        .from('custom_users')
        .select('first_name, last_name')
        .eq('id', studentId)
        .single();

      if (studentError || !student) {
        console.error('Error fetching student details:', studentError);
        return false;
      }

      // Calculate events for the next 12 weeks (3 months)
      const eventsToCreate = [];
      const startDate = new Date();
      const weeksToCreate = 12;
      
      for (let week = 0; week < weeksToCreate; week++) {
        const eventDate = new Date(startDate);
        eventDate.setDate(startDate.getDate() + (week * 7));
        
        // Find the next occurrence of the specified day of week
        const dayDiff = availabilitySlot.dayOfWeek - eventDate.getDay();
        if (dayDiff < 0) {
          eventDate.setDate(eventDate.getDate() + (7 + dayDiff));
        } else {
          eventDate.setDate(eventDate.getDate() + dayDiff);
        }

        // Create start and end times
        const [startHour, startMinute] = availabilitySlot.startTime.split(':').map(Number);
        const [endHour, endMinute] = availabilitySlot.endTime.split(':').map(Number);
        
        const startTime = new Date(eventDate);
        startTime.setHours(startHour, startMinute, 0, 0);
        
        const endTime = new Date(eventDate);
        endTime.setHours(endHour, endMinute, 0, 0);

        // Create event for teacher
        const teacherEvent = {
          id: uuidv4(),
          user_id: teacherId,
          event_type: 'class',
          title: `${course.title} - ${student.first_name} ${student.last_name}`,
          description: `${course.course_type} class with student ${student.first_name} ${student.last_name}`,
          start_time: startTime.toISOString(),
          end_time: endTime.toISOString(),
          metadata: {
            courseId,
            studentId,
            teacherId,
            courseType: course.course_type,
            courseTitle: course.title,
            isAutoGenerated: true
          }
        };

        // Create event for student
        const studentEvent = {
          id: uuidv4(),
          user_id: studentId,
          event_type: 'class',
          title: `${course.title} - with ${teacher.first_name} ${teacher.last_name}`,
          description: `${course.course_type} class with teacher ${teacher.first_name} ${teacher.last_name}`,
          start_time: startTime.toISOString(),
          end_time: endTime.toISOString(),
          metadata: {
            courseId,
            studentId,
            teacherId,
            courseType: course.course_type,
            courseTitle: course.title,
            isAutoGenerated: true
          }
        };

        eventsToCreate.push(teacherEvent, studentEvent);
      }

      // Insert all events
      const { error: insertError } = await supabase
        .from('user_events')
        .insert(eventsToCreate);

      if (insertError) {
        console.error('Error creating calendar events:', insertError);
        return false;
      }

      console.log(`Successfully created ${eventsToCreate.length} calendar events for recurring enrollment`);
      return true;

    } catch (error) {
      console.error('Error in createRecurringEvents:', error);
      return false;
    }
  };

  // Create calendar events for one-time courses
  const createOneTimeEvents = async (
    courseId: string,
    studentId: string,
    teacherId?: string,
    courseData?: any
  ) => {
    try {
      console.log('Creating one-time events for enrollment:', { courseId, studentId, teacherId });

      // Get course details
      const { data: course, error: courseError } = await supabase
        .from('courses')
        .select('title, duration, course_type, instructor_ids')
        .eq('id', courseId)
        .single();

      if (courseError || !course) {
        console.error('Error fetching course details:', courseError);
        return false;
      }

      // For group courses, use the first instructor if no specific teacher provided
      const effectiveTeacherId = teacherId || (course.instructor_ids && course.instructor_ids[0]);
      
      if (!effectiveTeacherId) {
        console.log('No teacher available for one-time course');
        return false;
      }

      // Get teacher details
      const { data: teacher, error: teacherError } = await supabase
        .from('custom_users')
        .select('first_name, last_name')
        .eq('id', effectiveTeacherId)
        .single();

      if (teacherError || !teacher) {
        console.error('Error fetching teacher details:', teacherError);
        return false;
      }

      // Get student details
      const { data: student, error: studentError } = await supabase
        .from('custom_users')
        .select('first_name, last_name')
        .eq('id', studentId)
        .single();

      if (studentError || !student) {
        console.error('Error fetching student details:', studentError);
        return false;
      }

      // For one-time courses, we'll create a placeholder event for next week
      // In a real scenario, this would be scheduled based on actual availability
      const eventDate = new Date();
      eventDate.setDate(eventDate.getDate() + 7); // Next week
      eventDate.setHours(14, 0, 0, 0); // 2 PM

      const endTime = new Date(eventDate);
      endTime.setHours(15, 0, 0, 0); // 1 hour duration

      const eventsToCreate = [];

      // Create event for teacher
      const teacherEvent = {
        id: uuidv4(),
        user_id: effectiveTeacherId,
        event_type: 'class',
        title: `${course.title} - ${student.first_name} ${student.last_name}`,
        description: `${course.course_type} class with student ${student.first_name} ${student.last_name}`,
        start_time: eventDate.toISOString(),
        end_time: endTime.toISOString(),
        metadata: {
          courseId,
          studentId,
          teacherId: effectiveTeacherId,
          courseType: course.course_type,
          courseTitle: course.title,
          isAutoGenerated: true,
          isOneTime: true
        }
      };

      // Create event for student
      const studentEvent = {
        id: uuidv4(),
        user_id: studentId,
        event_type: 'class',
        title: `${course.title} - with ${teacher.first_name} ${teacher.last_name}`,
        description: `${course.course_type} class with teacher ${teacher.first_name} ${teacher.last_name}`,
        start_time: eventDate.toISOString(),
        end_time: endTime.toISOString(),
        metadata: {
          courseId,
          studentId,
          teacherId: effectiveTeacherId,
          courseType: course.course_type,
          courseTitle: course.title,
          isAutoGenerated: true,
          isOneTime: true
        }
      };

      eventsToCreate.push(teacherEvent, studentEvent);

      // Insert events
      const { error: insertError } = await supabase
        .from('user_events')
        .insert(eventsToCreate);

      if (insertError) {
        console.error('Error creating calendar events:', insertError);
        return false;
      }

      console.log(`Successfully created ${eventsToCreate.length} calendar events for one-time enrollment`);
      return true;

    } catch (error) {
      console.error('Error in createOneTimeEvents:', error);
      return false;
    }
  };

  return {
    createRecurringEvents,
    createOneTimeEvents
  };
}
