// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lhsnzdonofweltzjpguf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imxoc256ZG9ub2Z3ZWx0empwZ3VmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ2OTMzMzcsImV4cCI6MjA2MDI2OTMzN30.KXDQ4Nt8rbRG_vjAU3cMrBD1vAhEhxlcZ338SFuZyx8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);